spdk-sys: Remove --without-vhost
The combination of --with-crypto and --without-vhost leads to build
failure:

/usr/bin/ld.bfd: /home/user/src/spdk/dpdk/build/lib/librte_pmd_qat.a(common_qat_qat_qp.c.o): in function `qat_crc_verify':
/home/user/src/spdk/dpdk/build-tmp/../drivers/crypto/qat/qat_sym.h:154: undefined reference to `rte_net_crc_calc'
/usr/bin/ld.bfd: /home/user/src/spdk/dpdk/build/lib/librte_pmd_qat.a(common_qat_qat_qp.c.o): in function `qat_crc_generate':
/home/user/src/spdk/dpdk/build-tmp/../drivers/crypto/qat/qat_sym.h:178: undefined reference to `rte_net_crc_calc'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/user/src/spdk/mk/spdk.app.mk:65: /home/jteh/src/spdk/build/bin/spdk_trace_record] Error 1
make[1]: *** [/home/user/src/spdk/mk/spdk.subdirs.mk:44: trace_record] Error 2

due to dpdk/012affe1 introducing a dependence on rte_net when building
with crypto, drop the latter.
The --without-vhost may have been introduced due to conflicting vhost
implementations in SPDK and DPDK, which appears to have been resolved
upstream.